### ISSUE TITLE
Sass partial changes are not detected

### ISSUE THREAD

**Issue by stilllife00** [symfony/AsseticBundle#341]
I am including sass partials on a `main.scss` file with
    
    @import "colors", "footer", "header";

The sass file is then compiled with 

    {% block stylesheets %}
            {% stylesheets filter="compass" filter="?uglifycss"
                "@EvoSscBundle/Resources/public/css/main.scss"
                output='css/evossc.css'
            %}
                <link rel="stylesheet" href="{{ asset_url }}" />
            {% endstylesheets %}
        {% endblock %}

But when I modify any of the partials the change is not reflected on Symfony. Only changing the main file works. I ve tried to put all the partials within the `stylesheets` tag instead, but it this way sass variables are not seen by other files.

**Comment by stof** [comment]
does it work if you use separate ``@import`` rules for each partial instead of putting them all in the same rule ?
Recent Assetic versions (I don't remember when it was implemented for Sass, so I cannot say what "recent" implies exactly) should support taking imported files into account for the detection of changes. but I don't think it supports multiple imports at once (I was not even aware this syntax was possible)

**Comment by stilllife00** [comment]
I've separated the rules but the problem remains. Based on the assetic repo I've also see that this should be fixed both for sass and compass filters , I am using the dev-master versions but still no luck...

**Comment by EvanPurkhiser** [comment]
Possibly related to #332. At least, the symptoms are the same.

**Comment by stilllife00** [comment]
Any idea  ? Can #332 be merged ?

**Comment by EvanPurkhiser** [comment]
#332 still needs more review before it can be merged, but I do believe it would solve your problem.

**Comment by stof** [comment]
#332 has been merged and is part of the 2.7.0 release
