### ISSUE TITLE
The file dev/assetic/routing.yml does not exist.

### ISSUE THREAD

**Issue by Oliboy50** [symfony/AsseticBundle#370]
I'm having an issue while warming up my cache with `assetic.use_controller: true`.

```
 [InvalidArgumentException]
  The file "/var/www/html/app/cache/dev/assetic/routing.yml" does not exist.
```

This happens since I decided to be able to configure my cache directory depending upon my environment:

```
# app/config_dev.yml

parameters:
    #%cache_dev_dir% === '%kernel.root_dir%/cache/'
    kernel.cache_dir: %cache_dev_dir%/dev

```

If I comment this parameter or if I `use_controller: false`, the error disappears.

By the way, when this error occurs, it creates a folder named `%cache_dev_dir%` at the project root.

EDIT: Just saw that there was a PR to handle this: #353

**Comment by stof** [comment]
Overwriting the ``kernel.cache_dir`` parameter from your config file is a very bad idea, and not a supported way to change the cache folder in Symfony.
It breaks things because you would now have different cache folders for the kernel ``Kernel::getCacheDir()`` and for the parameter.

See http://symfony.com/doc/current/cookbook/configuration/override_dir_structure.html#override-the-cache-directory for the proper way to resolve this

**Comment by Oliboy50** [comment]
Ok, Thanks. 

Actually, I read the documentation already, but it's not as handy as setting a parameter in `parameters.yml` (which is not committed to all the project contributors)... 

If you know a way to handle this properly... Would be very appreciated :)

**Comment by stof** [comment]
@Oliboy50 the issue is that it changes the cache only for half the places using it (for instance, the cache of the container would not depend on the value of the parameter, as the parameter is only available after loading the container)
